### ISSUE TITLE
DB data

### ISSUE THREAD

**Issue by yujinjung-git** [pbt98/APK_Crawler#2]
* INSERT crawled data in DB file

**Comment by pbt98** [comment]
* sqlite3를 사용하기로 결정함.
* 데이터베이스에 접근하기 위해서는 커서가 필요하다는 것을 공부함.
* create table, insert 문 등의 간단한 SQL문을 작성하는 방법을 공부함.
* 같은 이름의 테이블을 중복해서 만들수는 없음을 확인하였음.
