### ISSUE TITLE
Investigate dynamic recommend application list

### ISSUE THREAD

**Issue by pbt98** [pbt98/APK_Crawler#3]
* Find a static list of app each category
* Investigate why google's recommendations are different from user to user without login

**Comment by yujinjung-git** [comment]
* 구글 플레이 스토어 내 카테고리 별 맞춤추천 앱은 수시로 변경됨
* 구글 플레이 스토어 웹 / 앱 내 전체 인기 차트에서 static APK list 를 가져올 수 있음
* 앱에서는 카테고리 별 인기차트를 확인할 수 있지만 웹 사이트에서는 확인할 수 없음
* 카테고리가 지정되지 않은 전체 인기차트의 경우, 웹 사이트보다 앱에서 더 낮은 순위의 APK 목록까지 확인할 수 있음
